package com.tatucarreta.vistas;
import com.tatucarreta.data.SistemaDAO;import com.tatucarreta.ui.*;import javafx.scene.control.*;import javafx.scene.layout.*;import java.util.List;
public class VistaAnimales extends VistaCRUD{
 public VistaAnimales(){super("Animales","Registro maestro de ejemplares. La cantidad se calcula desde los registros operativos.",new String[]{"Animal","Especie","Nombre científico","Cantidad","Origen","Estado"});agregar.setText("＋ AGREGAR ANIMAL");cargar("");}
 protected List<SistemaDAO.Fila> consultar(String q){return SistemaDAO.animales(q);}protected List<SistemaDAO.Fila> consultarInactivos(String q){return SistemaDAO.animalesInactivos(q);}protected void activarRegistro(int id){SistemaDAO.activar("animales","id_animal",id);}protected void agregarNuevo(){form(0,null);}protected void editarSeleccionado(){var f=tabla.getSelectionModel().getSelectedItem();if(f!=null)form(f.id(),f);}
 protected void desactivar(int id){if(!SistemaDAO.animalPuedeEliminar(id)){info("No se puede eliminar","Este animal está asociado a un ingreso/acta o al Plantel Permanente. El historial debe conservarse.");return;}if(confirmarOK("Eliminar animal","¿Estás segura de que querés enviar este animal a registros inactivos?")){SistemaDAO.baja("animales","id_animal",id);cargar(buscador.getText());}}
 private void form(int id,SistemaDAO.Fila f){ComboBox<SistemaDAO.Opcion>esp=Estilos.combo();esp.getItems().setAll(SistemaDAO.especiesOpciones());Button nueva=Estilos.botonSec("＋ Especie");HBox espBox=new HBox(8,esp,nueva);HBox.setHgrow(esp,Priority.ALWAYS);nueva.setPrefWidth(115);TextField vul=Estilos.campo("Nombre común"),cient=Estilos.campo("Nombre científico (opcional)"),orig=Estilos.campo("Origen o procedencia");
  if(f!=null){vul.setText(f.c().get(1));cient.setText(f.c().get(3));orig.setText(f.c().get(5));esp.getItems().stream().filter(o->o.texto().equals(f.c().get(2))).findFirst().ifPresent(esp::setValue);}nueva.setOnAction(e->crearEspecie(esp));GridPane g=Formulario.grid();Formulario.add(g,0,"Especie",espBox,true);Formulario.add(g,1,"Nombre vulgar",vul,true);Formulario.add(g,2,"Nombre científico",cient,false);Formulario.add(g,3,"Origen",orig,false);
  Label nota=new Label("La cantidad no se carga aquí: se actualiza desde Ingresos, Plantel, nacimientos y fallecimientos.");nota.setWrapText(true);nota.setStyle("-fx-background-color:"+Estilos.VERDE_SUAVE+";-fx-text-fill:"+Estilos.VERDE_OSCURO+";-fx-padding:10;-fx-background-radius:8;");g.add(nota,1,4);Dialog<ButtonType>d=Formulario.dialog(id==0?"Nuevo animal":"Modificar animal",g);d.showAndWait().ifPresent(x->{if(x==ButtonType.OK)try{if(esp.getValue()==null||!validar(vul.getText()))throw new IllegalArgumentException("Elegí una especie y completá el nombre del animal.");if(confirmarOK(id==0?"Agregar animal":"Guardar cambios",id==0?"¿Estás segura de que querés agregar este animal?":"¿Querés guardar los cambios del animal?")){SistemaDAO.guardarAnimal(id,esp.getValue().id(),vul.getText().trim(),cient.getText().trim(),orig.getText().trim());cargar(buscador.getText());}}catch(Exception e){error("No se pudo guardar",e.getMessage());}});}
 private void crearEspecie(ComboBox<SistemaDAO.Opcion>esp){TextField n=Estilos.campo("Nombre de la especie");GridPane g=Formulario.grid();Formulario.add(g,0,"Nombre",n,true);Dialog<ButtonType>d=Formulario.dialog("Crear especie sin salir del animal",g);d.showAndWait().ifPresent(x->{if(x==ButtonType.OK&&validar(n.getText())&&confirmarOK("Agregar especie","¿Querés agregar esta especie?")){int id=SistemaDAO.guardarEspecie(0,n.getText().trim());esp.getItems().setAll(SistemaDAO.especiesOpciones());esp.getItems().stream().filter(o->o.id()==id).findFirst().ifPresent(esp::setValue);}});}
}
